name: flutter_base
description: A base flutter project created by Hien Le
version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  get_storage: ^2.0.3
  logger: ^2.3.0
  supercharged: ^2.0.0
  velocity_x: ^4.2.0
  connectivity_plus: ^6.0.3
  jwt_decoder: ^2.0.1
  freezed_annotation: ^2.0.3
  http: ^1.2.1
  intl: ^0.19.0
  simple_animations: ^5.0.0+2
  adaptive_theme: ^3.1.1
  lottie: ^3.1.2
  local_auth: ^2.1.2
  json_annotation: ^4.9.0
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.1.5
  flutter_svg: ^2.0.9
  modal_bottom_sheet: ^3.0.0
  awesome_snackbar_content: ^0.1.0
  timeago: ^3.3.0
  url_launcher: ^6.2.6
  crypto: ^3.0.2
  badges: ^3.0.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.1
  hive_flutter: ^1.1.0
  sentry_flutter: ^8.2.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mockito: null

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
