name: h_flutter_base
description: The flutter base for easy developing.
version: 0.0.1
author: Hieren Lee
homepage: https://github.com/hienlh/h_flutter_base

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
