name: flutter_base
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  logger: ^2.0.2+1
  supercharged: ^2.0.0
  velocity_x: ^4.1.1
  connectivity_plus: ^5.0.1
  graphql_flutter: ^5.1.2
  jwt_decoder: ^2.0.1
  freezed_annotation: ^2.0.3
  firebase_crashlytics: ^3.0.12
  firebase_core: ^2.5.0
  http: ^1.1.0
  intl: ^0.18.1
  firebase_remote_config: ^4.3.3
  firebase_analytics: ^10.1.1
  simple_animations: ^5.0.0+2
  adaptive_theme: ^3.1.1
  lottie: ^3.0.0
  firebase_auth: ^4.2.6
  local_auth: ^2.1.2
  json_annotation: ^4.6.0
  flutter_facebook_auth: ^6.0.2
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.5
  flutter_svg: ^2.0.9
  modal_bottom_sheet: ^3.0.0-pre
  awesome_snackbar_content: ^0.1.0
  timeago: ^3.3.0
  url_launcher: ^6.1.5
  crypto: ^3.0.2
  badges: ^3.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lints: null
  mockito: null

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
