// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz7ico5UXE7VDHLiE6T8KgaN5hcfAZTRY',
    appId: '1:238322610807:web:7c770584cd9d85d9b50c72',
    messagingSenderId: '238322610807',
    projectId: 'flutter-base-493f6',
    authDomain: 'flutter-base-493f6.firebaseapp.com',
    storageBucket: 'flutter-base-493f6.appspot.com',
    measurementId: 'G-Q4BCB7B69B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO4bR9UM7Cbzs0UkzpfHN9lKvxrJw-s4M',
    appId: '1:238322610807:android:4e68a06be04c1a52b50c72',
    messagingSenderId: '238322610807',
    projectId: 'flutter-base-493f6',
    storageBucket: 'flutter-base-493f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgXgfXCTiOYx23jgckZHhy3RjaaZ0Gr2k',
    appId: '1:238322610807:ios:e6631dcc91a4ffc3b50c72',
    messagingSenderId: '238322610807',
    projectId: 'flutter-base-493f6',
    storageBucket: 'flutter-base-493f6.appspot.com',
    iosClientId: '238322610807-8qbcv6v3qgo4hmq8h3bb6eth6q15vc7m.apps.googleusercontent.com',
    iosBundleId: 'com.hienlh.flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgXgfXCTiOYx23jgckZHhy3RjaaZ0Gr2k',
    appId: '1:238322610807:ios:681fc8d0b35579dbb50c72',
    messagingSenderId: '238322610807',
    projectId: 'flutter-base-493f6',
    storageBucket: 'flutter-base-493f6.appspot.com',
    iosClientId: '238322610807-aahqhpaf3vv9ge2g366jd58jsgs8jjv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.hFlutterBase',
  );
}
