// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStg {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw3Q1jALmsG4JiVQtZutOkhk8RXaBODZQ',
    appId: '1:654334503118:web:08c6e518df832fd56e089f',
    messagingSenderId: '654334503118',
    projectId: 'flutter-base-dev',
    authDomain: 'flutter-base-dev.firebaseapp.com',
    storageBucket: 'flutter-base-dev.appspot.com',
    measurementId: 'G-39Q8MBCML8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYeG3eOa9rTSroilqyFh44QzbghfEr_FU',
    appId: '1:654334503118:android:682c3e2ae87637786e089f',
    messagingSenderId: '654334503118',
    projectId: 'flutter-base-dev',
    storageBucket: 'flutter-base-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0PPTh7KGNKWqhanGH4UjEAzY6qG-0L8E',
    appId: '1:654334503118:ios:2b5928d48c7cca676e089f',
    messagingSenderId: '654334503118',
    projectId: 'flutter-base-dev',
    storageBucket: 'flutter-base-dev.appspot.com',
    iosClientId:
        '654334503118-4drvm3c1s5ip108lgs5jrve91rrsb9k4.apps.googleusercontent.com',
    iosBundleId: 'com.hienlh.flutter.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0PPTh7KGNKWqhanGH4UjEAzY6qG-0L8E',
    appId: '1:654334503118:ios:9072551d5820a6d96e089f',
    messagingSenderId: '654334503118',
    projectId: 'flutter-base-dev',
    storageBucket: 'flutter-base-dev.appspot.com',
    iosClientId:
        '654334503118-dtetl4f19ikrtl03flg99kp8itfjjm5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.hFlutterBase',
  );
}
